### PR TITLE
Add feature to use sublime settings for syntax checkers.

### PR DESCRIPTION
**Pull request by zehome**
This will not modify the current behavior of your system. It will just enable the possibility to override checkers using sublime settings.

### CODE REVIEW

**Comment by vorushin** [comment]
Did you push your new commits to zehome:master?

**Comment by zehome** [comment]
I pushed -f a rebase so you can see directly see modified files entirely instead of patches on patches (in the pull request the patch is updated in other words) (in theory)

**Comment by vorushin** [comment]
Unfortunately I see no changes in the pull request.

**Comment by zehome** [comment]
My rebase was wrong. Should be better

**Comment by vorushin** [comment]
The code needed a little fix - 8622a78. JFYI 
//cc @zehome

**Pull request merged**
